apiVersion: v1
kind: Service
metadata:
  name: packt-modern-api-development-chapter09-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    app: packt-modern-api-development-chapter09
